[package]
name = "imageops"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.3"
rayon = "1.5.3"
# itertools = "0.10.3"

[profile.dev]
opt-level = 3

[profile.release]
opt-level = 3


